import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="sticky top-0 z-30 w-full bg-white/80 dark:bg-neutral-950/80 backdrop-blur border-b border-neutral-100 dark:border-neutral-800 py-3 px-6 flex items-center justify-between shadow-sm">
          <a
            href="#"
            className="flex items-center gap-2 font-extrabold text-xl tracking-tight text-neutral-900 dark:text-neutral-100"
          >
            <span className="text-blue-600">&#9673;</span>
            Piyawong
          </a>
          <div className="flex gap-6 text-base font-medium">
            <a href="#about" className="hover:text-blue-600 transition-colors">
              About
            </a>
            <a href="#skills" className="hover:text-blue-600 transition-colors">
              Skills
            </a>
            <a
              href="#projects"
              className="hover:text-blue-600 transition-colors"
            >
              Projects
            </a>
            <a
              href="#contact"
              className="hover:text-blue-600 transition-colors"
            >
              Contact
            </a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
